#################################
# Gnanamuthu Paul Pandian
# 31st August 2022
# Gelos Menu Page

# include python library and modules required for the program
import sys
import time
import string
import random


#######################
# login function
def login():
    # Opens accounts txt file
    accounts_file = open("accounts.txt", "r")
    # input username and password from the user
    username = input('Enter your Gelos username: ')
    password = input('Enter your Gelos password: ')

    # Read the lines
    for line in accounts_file:
        # Split the line by space between the username and password
        login_details = line.replace("\n", "").split(" ")
        # If the credentials match then login to Gelos systems else prompt it is incorrect and return to main menu
        if username == login_details[0]:
            complete = True
            print('User is recognised in Gelos Enterprises system')
            if password == login_details[1]:
                print('User is successfully logged in to Gelos Enterprises ')
            break

        else:
            complete = False
            continue
    if complete == True:
        print("Welcome to Gelos Enterprises user portal")
    else:
        print("Username and / or Password not registered in the Gelos system")


# REGISTER New Users
def register():
    global userName
    # enter username without any space
    while True:
        userName = input('Enter a username with no spaces:\n')
        if ' ' in userName:
            print("Try again")
        # username length must be atleast 4
        elif len(userName) < 4:
            print("Username must be atleast 4 characters long")
        else:
            print("username is valid")
            print(userName)
            break

    # save username to document

    file = open("accounts.txt", "a+")
    file.write(userName)
    file.write(" ")
    file.close()
    print("username has been saved")
    userChoice()
    # password function


def userChoice():
    global userEntered
    userEntered = input("Do you prefer entering your own password? if so, type A: ").upper()  # User selects to enter
    # password or to be generated by system

    if userEntered == "A":
        print("user choose A to enter password")
        password()
    else:
        print("user pressed other keys, password is generated by the Gelos system!")
        passwordGen()


def password():
    global pwd, msg
    # user entered password with minimum length of 10 and requires combination of characters for validity
    passwordLength = 10

    pwd = input("Please enter your password: ")
    if len(pwd) < passwordLength:
        msg = "Password must be more than 10 characters"
        print(msg)
        return password()
    elif pwd.isalpha():
        msg = "password must contains letters and numbers"
        print(msg)
        return password()
    elif pwd.isnumeric():
        msg = "password must contain numbers and letters"
        print(msg)
        return password()
    else:
        print("valid password")
        file = open("accounts.txt", "a+")
        file.write(pwd + "\n")
        file.close()
        print("password has been saved")
        print(pwd)


# password generator function
def passwordGen():
    global paw
    # Required length of the password for Gelos Enterprise Users
    length = 10
    # Password combinations to select from
    char = "abcdefghijklmnopqrstuvwxyz01234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()?"
    # Password generator
    paw = "".join(random.sample(char, length))
    # Save the username and password to the file
    file = open("accounts.txt", "a")
    file.write(paw + "\n")
    print('Your username and password has been registered. ')
    print(paw)
    print("user is now registered and can login using the credentials")
    file.close()
    print("Your login details have been saved. You can use this credentials to login ")

# Exit function
def exit():
    # Halts the program for two seconds
    print("Leaving Gelos Enterprises system in 2 seconds ... ")
    time.sleep(2)  # Exits the program
    sys.exit()  # system exit


# Main Menu Generator
def menu():
    print("MAIN MENU")
    print("1. Login")
    print("2. Register")
    print("3. Exit")


# main menu
userOption = True
while userOption:
    menu()
    userOption = input("Please make a selection from the main menu: ")
    if (userOption == "1"):
        login()  # action login request
    elif (userOption == "2"):
        register()  # action register request
    elif (userOption == "3"):
        exit()  # exit program
    else:
        print("Please select one of the options")
